### ISSUE TITLE
Why custom pin icon in iOS bigger than Android?

### ISSUE THREAD

**Issue by amay077** [amay077/Xamarin.Forms.GoogleMaps#40]
I use `BitmapDescriptorFactory.FromBundle` or `BitmapDescriptorFactory.FromStream` in custom pin icon.
This is same image size but iOS pin icon size is bigger than Android.

![2016-07-14 03 10 25](https://cloud.githubusercontent.com/assets/401369/16896029/42d19966-4bc2-11e6-84b0-716d2b68ad91.png)

I don't know why such a happen.
This is not Xamarin.Forms.GoogleMaps's problem, because it does not process source image.

I wonder what is due?
- Google Maps SDK for iOS's design?
- Related on Retina display?
- iOS side is correct, Android side is wrong?
- "@2x" image can solves this?
- `Resources.DisplayMetrics` can solves this?

Any ideas?

**Comment by bbartlett** [comment]
I just read about a similar problem on the "TK.CustomMap" component: "Custom pin icon looks large and blury on iOS". (See [https://github.com/TorbenK/TK.CustomMap/issues/100](url) .)

From [https://github.com/TorbenK/TK.CustomMap/issues/100#issuecomment-230470781](url) , in their case the problem seems to be due to using a `StreamImageSource`; since in that case there is no `@2x` file name, `UIImage` cannot guess the proper size.

**Comment by jungotakemura** [comment]
素晴らしいライブラリをありがとうございます。

UIImage.LoadFromDataには、第二引数でscaleを指定することが可能です。

BitmapDescriptorExtensions.ToUIImageで

UIImage.LoadFromData(NSData.FromStream(self.Stream), UIScreen.MainScreen.Scale);

手元ではこれでうまくいっているように見えます。
(iOSのバージョンなどで縛りがあるかもしれません)

別件で気になっているのは、これでマーカーをたくさん作ると、同一ストリームを指定してもメモリを大量に消費しないか？ということです。

**Comment by damianun** [comment]
Solutiong suggested by @jungoross is working.
As a workaround I am overwritng Icon property on Pin.NativeObject using the above method, but @amay077 could you please include the above fix in your next release?

Thank you in advance

**Comment by ormedo** [comment]
I can't undestand @jungoross  response because its in Japanese, could be translated?

**Comment by amay077** [comment]
Hi @ormedo ,
I am fixing it in https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/417. 

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/5103eb350ba2fb5af5a8134e75575ad594cfceec/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.iOS/Extensions/BitmapDescriptorExtensions.cs#L17-L25

This solution is provided from @jungoross that resize image using ``MainScreen.Scale`` .

**Comment by amay077** [comment]
I released [2.3.0-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.3.0-beta1) than includes fix this issue.

**Comment by amay077** [comment]
@jungoross さん、返事が遅くなってすみません。
貴方が提案していただいた修正を適用して大丈夫そうだったので v2.3.0-beta1 に組み込みました。

BitmapDescriptorType.Bundle の方も同じ問題があったので、同じように修正しています。
リサイズの為にメモリを消費しそうなのはその通りだと思いますが、仕方ないですね。

**Comment by jungoross** [comment]
ご対応ありがとうございました。小まめなアップデートのご尽力に大変感謝しております。

**Comment by karenlll** [comment]
I still have the same problem although I have instaled the 3.3.0 version in my project, any suggestion?

**Comment by BillyMartin1964** [comment]
The pins are huge on Xamarin Forms UWP. Any fix for this?

**Comment by de1081** [comment]
The pins are too small for me on Android. Does anyone know how to make the pins bigger on Android?

**Comment by HYoung1484** [comment]
Same as @karenlll, version 3.3.0 installed and I have this problem.
