### ISSUE TITLE
Pin label not shown on iOS 13.1.2 (on real devices)

### ISSUE THREAD

**Issue by galadril** [amay077/Xamarin.Forms.GoogleMaps#663]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.2.1
* Xamarin.Forms - 4.2.0.848062

### PLATFORMS
- [x] iOS | >=13.1.2 

### ACTUAL BEHAVIOR
I've created a pin with Label and Address, but only the address is visible (see screenshot below)

### ACTUAL SCREENSHOTS/STACKTRACE
![afbeelding](https://user-images.githubusercontent.com/14561640/66996944-e017d480-f0d1-11e9-9fe5-f0af22233e7e.png)

### EXPECTED BEHAVIOR
I actually set a label to that pin.. it works on a emulator thats on ios 13.1:
![afbeelding](https://user-images.githubusercontent.com/14561640/66997010-f9208580-f0d1-11e9-9edf-1804c0982a1c.png)

### HOW TO REPRODUCE
1. On a real device, create a map with a pin that contains a label and address
2.  Click on the pin to open the info window. it now only shows the address

**Comment by ppeau** [comment]
the issue comes from the new theme "dark mode" in ios 13. If you switch it back to the light mode.
You'll see your label again.

Something is not compatible with the new dark mode but I wonder if it may comes from the pin in Xamarin.Forms.Maps rather than Xamarin.Forms.GoogleMaps ?

**Comment by amay077** [comment]
I think this is related with Google Maps SDK for iOS or Xamarin.Google.iOS.Maps.

We should wait for fix in these.

**Comment by amay077** [comment]
I found fixed libraries.

* https://developers.google.com/maps/documentation/ios-sdk/releases#version_350_-_october_08_2019
* https://www.nuget.org/packages/Xamarin.Google.iOS.Maps/3.5.0

I will depends Xamarin.Google.iOS.Maps 3.5.0.

**Comment by galadril** [comment]
Oh that would be awesome thanks!

**Comment by amay077** [comment]
Fixed in https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/3.3.0 .

**Comment by galadril** [comment]
Great! Aldo i thought that it all worked but i get a linker exception:
```

warning : directory not found for option '-FGMps-3.5.0/Maps/Frameworks'
error : linker command failed with exit code 1 (use -v to see invocation)
error : warning: directory not found for option '-FGMps-3.5.0/Maps/Frameworks'
```

**Comment by amay077** [comment]
Do you update Deployment target to 8.0 in your iOS App's ``info.plist`` ?

Or ...

Clear and rebuild your solution:

* Delete /packages directory
* Delete /.vs directory
* Delete /bin, /obj directory each projects

**Comment by galadril** [comment]
i had the deployment target on 11.0.. let me check if the clean/rebuild works

**Comment by galadril** [comment]
I still get this linker exceptions as soon as i update Xamarin.Google.iOS.Maps to 3.5.0.

**Comment by amay077** [comment]
Could you try [XFGoogleMapSample](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/master/XFGoogleMapSample) and check difference between it and your proj.

**Comment by galadril** [comment]
Also the Sample project gives the same builderror for me. (#665 as wel)

**Comment by rdonasco** [comment]
> Great! Aldo i thought that it all worked but i get a linker exception:
> 
> ```
> warning : directory not found for option '-FGMps-3.5.0/Maps/Frameworks'
> error : linker command failed with exit code 1 (use -v to see invocation)
> error : warning: directory not found for option '-FGMps-3.5.0/Maps/Frameworks'
> ```
> 
> Framework not found GoogleMaps

I have the same problem
  MTOUCH: error MT5202: Native linking failed. Please review the build log.
  clang: error : linker command failed with exit code 1 (use -v to see invocation)
  error MT5209:  Native linkingerror : framework not found GoogleMaps
  error MT5209:  Native linkingerror : warning: directory not found for option '-FGMps-3.5.0/Base/Frameworks'
  error MT5209:  Native linkingerror : warning: directory not found for option '-FGMps-3.5.0/Maps/Frameworks'

**Comment by rdonasco** [comment]
> Could you try [XFGoogleMapSample](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/master/XFGoogleMapSample) and check difference between it and your proj.

strange, the sample works for me. :(, but my own project does not build.

**Comment by AlonikiX** [comment]
> > Could you try [XFGoogleMapSample](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/master/XFGoogleMapSample) and check difference between it and your proj.
> 
> strange, the sample works for me. :(, but my own project does not build.

The same here. I am using Xamarin.Forms 4.3, could this be a problem?

**Comment by iamlawrencev** [comment]
Could be related to #666

**Comment by rdonasco** [comment]
Here's how I solved it.
With your project still using nuget packages 
- Xamarin.Forms.GoogleMaps v3.3.0
- Xamarin.Google.IOS.Maps v3.5.0

1. Remove the following directory and its contents. 
`/Users/rdonasco/.nuget/packages/xamarin.google.ios.maps/3.5.0`
2. Restore your nuget packages, this will recreate the v3.5.0 directory and its contents.
3. Downgrade your project to use nuget packages
- Xamarin.Forms.GoogleMaps v3.2.1
- Xamarin.Google.IOS.Maps v3.1.0
4. Build your project - this should go back to successful build.
5. Upgrade your project to use
- Xamarin.Forms.GoogleMaps v3.3.0
- Xamarin.Google.IOS.Maps v3.5.0
6. Rebuild your project.
