### ISSUE TITLE
iOS build error with v3.3.0

### ISSUE THREAD

**Issue by stesvis** [amay077/Xamarin.Forms.GoogleMaps#665]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.3.0
* Xamarin.Forms - 4.3.0
* 

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

Build error:
/Users/stesvis/Documents/projects/levitica/livedispatch/LiveDispatch.Mobile/LiveDispatch.Mobile.iOS/error MT5209: Error: warning: directory not found for option '-FGMps-3.5.0/Maps/Frameworks' (LiveDispatch.Mobile.iOS) Native linking

### EXPECTED BEHAVIOR

It should build with no errors

### HOW TO REPRODUCE

1. Install the latest version
2. Build the iOS project

**Comment by galadril** [comment]
i have the same issue.

**Comment by amay077** [comment]
Is this link helps you?

* https://stackoverflow.com/search?q=warning%3A+directory+not+found+for+option

I think it is related with Xcode project setting.

**Comment by amay077** [comment]
I can not reproduce.
Probably it is not related Xamarin.Forms.GoogleMaps also not related Xamarin.Forms .

I think it is Xamarin.iOS with GoogleApisForiOSComponents issue.

Please try using [Xamarin.Google.iOS.Maps 3.5.0](https://www.nuget.org/packages/Xamarin.Google.iOS.Maps/3.5.0) with Xamarin.iOS(NOT Xamarin.Forms) and if you can see same error, report to [Xamarin team](https://github.com/xamarin/GoogleApisForiOSComponents/issues).

**Comment by hajuuk** [comment]
https://github.com/xamarin/GoogleApisForiOSComponents/issues/324

I submitted this issue to Xamarin repo and finally solved by explicit add a NuGet package `Xamarin.Build.Download`.

https://github.com/xamarin/GoogleApisForiOSComponents/issues/324#issuecomment-545725609

**Comment by galadril** [comment]
Thanks @hajuuk 
That solves it indeed

**Comment by amay077** [comment]
@hajuuk, you did great work! 👍

**Comment by stesvis** [comment]
Awesome! Side note, you have to target at least **iOS 10** otherwise you still get build errors.

**Comment by stesvis** [comment]
@hajuuk do we need to install it only on the iOS project or all three?

**Comment by hajuuk** [comment]
> @hajuuk do we need to install it only on the iOS project or all three?

I tested, install it for the iOS project is sufficient.

**Comment by erdugen** [comment]
I added the Xamarin.Build.Download nuget package to my project and then upgraded it to v.3.3.0. But the problem did not disappear. Anybody have any ideas?

![image](https://user-images.githubusercontent.com/4970900/67547045-a022a400-f706-11e9-997e-d2088bd7c3cc.png)

**Comment by stesvis** [comment]
@erdugen i had to target minimum iOS 10.0

**Comment by erdugen** [comment]
> @erdugen i had to target minimum iOS 10.0

@stesvis Thank you. Problem solved in this way.
